version: '3'

services:

  sourcerer:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-sourcerer-app
    stdin_open: true
    tty: true
    volumes:
      - ~/.sourcerer/data:/root/.sourcerer/data
    working_dir: /projects
